### ISSUE TITLE
MAPA MENTAL NESTOR CRUZ LEON

### ISSUE THREAD

**Issue by Nestor283** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Nestor283#3]
![CONJUNTOS_Y_RELACIONES_MAPA_MENTAL_NESTOR_CRUZ_LEON](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-Nestor283/assets/143577212/a8129312-b7c3-45ba-868b-d88c7453e6c0)

**Comment by 00Asaf00** [comment]
- Manejo: 25%
- Relaciones: 20%
- Calidad: 15%
- Jerarquía: 25%

Calificación:
(85%)/100*20 = 17/20

Comentarios:

- Buen manejo de la información pero la resolución y el diseño no ayudan mucho.

- La calidad carece un poco, pero no deja de estar completa la información.

Evaluado por el Equipo de Edgar Iván

**Comment by josealfredo79** [comment]
Revisado...
